services:
    postgres:
        image: postgres:18-alpine
        restart: always
        ports:
            - "${POSTGRES_PORT}:${POSTGRES_PORT}"
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - ./res/dump.sql:/docker-entrypoint-initdb.d/dump.sql
            - pgdata:/var/lib/postgresql
    mongo:
        image: mongo:8.2.11
        restart: always
        ports:
            - "${MONGO_PORT}:${MONGO_PORT}"
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
            MONGO_INITDB_DATABASE: ${DB_NAME}
        volumes:
            - mongodata:/data/db
        healthcheck:
            test: echo 'db.runCommand("ping").ok | mongosh --quiet'
            interval: 5s
            timeout: 5s
            retries: 5
    mongo-setup:
        image: python:3.11-slim
        depends_on:
            mongo:
                condition: service_healthy
        volumes:
            - ./res/setup.py:/app/setup.py
            - ./res/schemas:/app/schemas
        working_dir: /app
        environment:
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME: ${DB_NAME}
            MONGO_HOST: mongo # container-to-container
            MONGO_PORT: 27017
        command: sh -c "pip install --no-cache-dir pymongo python-dotenv && python setup.py"
volumes:
    pgdata:
        driver: local
    mongodata:
        driver: local
