services:
    postgres:
        image: postgres:latest
        restart: always
        ports:
            - "${POSTGRES_PORT}:${POSTGRES_PORT}"
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - ./res/dump.sql:/docker-entrypoint-initdb.d/dump.sql
            - pgdata:/var/lib/postgresql/data
    mongo:
        image: mongo:latest
        ports:
            - "${MONGO_PORT}:${MONGO_PORT}"
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
            MONGO_INITDB_DATABASE: ${DB_NAME}
        volumes:
            - mongodata:/data/db
volumes:
    pgdata:
        driver: local
    mongodata:
        driver: local
