services:
    db:
        image: postgres:16-alpine
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_HOST: ${DB_HOST}
            POSTGRES_PORT: ${DB_PORT}
        volumes:
            - ./res/dump.sql:/docker-entrypoint-initdb.d/dump.sql
            - pgdata:/var/lib/postgresql/data
volumes:
    pgdata:
        driver: local
