CREATE USER etl_user WITH PASSWORD 'etlUserPassword';

GRANT CONNECT ON DATABASE dw_ufs TO etl_user;

GRANT USAGE ON SCHEMA public TO etl_user;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA public
TO etl_user;

GRANT USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA public
TO etl_user;